# Конфигурация системы напоминаний для Task Manager Bot

reminders:
  # Тип планировщика: "smart" (event-driven) или "polling" (старый)
  scheduler:
    type: "smart"  # Рекомендуется: smart

    # Настройки для smart scheduler
    initial_lookahead_hours: 72  # Загрузка напоминаний при старте (3 дня)
    daily_reload_window: [48, 72]  # Окно догрузки раз в сутки (с 48 до 72 часов)
    cleanup_time: "23:55"  # Время очистки старых напоминаний
    config_reload_time: "03:00"  # Время перезагрузки конфигурации
    old_reminders_retention_days: 7  # Хранить отправленные напоминания N дней

  # DEPRECATED: используется только для старого polling scheduler
  # check_interval: 3600  # Интервал проверки в секундах (только для type: "polling")

  # Настройки напоминаний о дедлайнах
  deadline_reminders:
    # Напоминания создаются автоматически для задач с датами
    # Можно указать несколько напоминаний с разными интервалами

    # Формат:
    # - days_before: количество дней до дедлайна (0 = в день дедлайна)
    #   time: время напоминания в формате "HH:MM"

    - days_before: 2
      time: "12:00"  # За 2 дня в 12:00

    - days_before: 1
      time: "20:00"  # За день до в 20:00

    - days_before: 0
      time: "10:00"  # В день дедлайна в 10:00

  # Настройки напоминаний для задач с точным временем
  time_based_reminders:
    # Напоминания для задач, у которых указано конкретное время выполнения
    # Например: "Встреча в 15:00", "Позвонить в 10:30"

    enabled: true

    # Напоминания за N часов до события
    # Можно указать несколько интервалов
    hours_before:
      - 3  # За 3 часа
      - 1  # За 1 час

    # Дополнительное напоминание за N минут (опционально)
    # minutes_before:
    #   - 30  # За 30 минут
    #   - 15  # За 15 минут

  # Настройки проверки условий
  condition_checks:
    # Интервал проверки условий (в секундах)
    # 86400 = 1 день, 43200 = 12 часов
    default_interval: 86400  # 1 день

    # Время для проверки условий (если не указано конкретное время)
    default_time: "10:00"

  # Утренние напоминания (для активных задач)
  morning_reminders:
    enabled: true
    time: "09:00"

# Общие настройки
general:
  # Временная зона (для корректной работы с датами)
  timezone: "Europe/Moscow"

  # Минимальный интервал между напоминаниями (в минутах)
  min_reminder_interval: 60
